#!/bin/bash
#
# Simple wrapper script for UAI Inference Competition 2014.
# by Lars Otten, July 2014

# Note: $3 is ignored for MPE.

echo "Invoked as '$0 $*'"

if [ "$4" != "MPE" ] ; then
  if [ "$4" != "MMAP" ] ; then
    echo "Expecting MPE or MMAP task as fourth argument"
    exit 1
  fi
fi

if [ "${INF_TIME}" == "" ] ; then
  echo "Environment variable for time limit not found."
  exit 1
fi

if [ "${INF_MEMORY}" == "" ] ; then
  echo "Environment variable for memory limit not found."
  exit 1
fi

echo "Found time limit ${INF_TIME} and memory limit ${INF_MEMORY}."

# Determine memory limit for mini buckets (to leave space for search)  
MEMLIMIT=$((${INF_MEMORY}*1000-350))

if [ "$4" == "MMAP" ] ; then
  MMAP=" --mmap-file $3"
fi

# set/unset to enable/disable breadth-rotate AOBB 
ROTATE=" --rotate"

# set/unset to enable/disable Alex's mini buckets with moment matching
MATCH=" --match 1"

# set/unset to enable/disable Kalev's minfill ordering code
CVO=" --cvo"

# MPLP/JGLP settings for different time limits
MPLP20S="--mplps 2 --jglps 2"
MPLP20M="--mplps 30 --jglps 30 --mplp 500 --jglp 250"
MPLP60M="--mplps 60 --jglps 60 --mplp 2000 --jglp 1000"

# fixed random seed
SEED=4242

# 20 second timelimit
if [ ${INF_TIME} -eq 20 ] ; then
  ./daooptW -f $1 -e $2 ${MMAP} --seed ${SEED} --slsX 2 --slsT 2 -t500 --orderTime 3 -m125 -i15 -a1 ${ROTATE} ${MATCH} ${CVO} ${MPLP20S}
  rc=$?

# 20 minute timelimit
elif [ ${INF_TIME} -eq 1200 ] ; then
  ./daooptW -f $1 -e $2 ${MMAP} --seed ${SEED} --slsX 10 --slsT 6 -t10000 --orderTime 60 -m${MEMLIMIT} -i25 -a2 ${ROTATE} ${MATCH} ${CVO} ${MPLP20M}
  rc=$?
  
# 1 hour timelimit
elif [ ${INF_TIME} -eq 3600 ] ; then
  ./daooptW -f $1 -e $2 ${MMAP} --seed ${SEED} --slsX 20 --slsT 10 -t30000 --orderTime 180 -m${MEMLIMIT} -i35 -a2 ${ROTATE} ${MATCH} ${CVO} ${MPLP60M}
  rc=$?

# unknown timelimit
else
  echo "Only timelimit 60, 1200, 3600 are supported."
  exit 1
fi

echo "Exited with return code ${rc}."
